### ISSUE TITLE
Unit's will obtain navigation paths from other units.

### ISSUE THREAD

**Issue by Ashley-exe** [Shinkson47/UniX6#67]
Somehow, units are obtaining the node paths from other units. I can't figure this out.

**Comment by Shinkson47** [comment]
I spent ages thinking this was thread safety, but i think i've figured it out.

The A* library X6 uses a static final list in a utility method when creating the path. This static final list is what was returned to the unit.

'Cause of this, all of the units were fighting over the use of the same mutable list.

Not so simple hunting to find this, but the fix is simple; just create a copy of the list before storing it in the unit.

**Comment by Shinkson47** [comment]
As much as i believe that this is the issue and the correct fix it's difficult to test this absolutely, so i left in the guard clause and added a throw to make it abundantly clear if the issue happens again that this has not been fixed.
